#page title
page_title                                : Progress

# App Info
ios_app_id                                : 1548213909

appstore_link                             : https://apps.apple.com/app/apple-store/id1548213909?mt=8 
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Progress                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Progress is an app for iOS & macOS designed to....

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

your_name                                 : Shayes Apps LLC                             
your_link                                 : https://www.shayesapps.com                                             
email_address                             : support@shayesapps.com
facebook_username                         : shayesapps                                         
twitter_username                          : shayesapps

features                                  :

  - title                                 : TBD
    description                           : TBD
    fontawesome_icon_name                 : star


# Theme Settings
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman